### ISSUE TITLE
social icons not visible in footer

### ISSUE THREAD

**Issue by bssb** [mattbutton/silhouette-hugo#4] opened 2019-01-18 02:37 UTC
The social icons disappear from the footer when the page width is less than 992px. Is this the intended behavior? If not, I could make a PR if you want.

**Comment by mattbutton** [comment] 2019-01-18 09:47
Thanks for spotting. No, that isn't the intended behavior.

Yes please, a PR would be great.

**Comment by mattbutton** [comment] 2019-01-25 10:07
Fixed in #5

**Closed as completed** 2019-01-25 10:07 UTC
